In [36]:
import numpy as np

Arr1 = np.full((5, 5), 1.)
Arr2 = np.full((5, 5), 5)

sumArr = Arr1 + Arr2
print(sumArr)

for i in range(len(Arr1)):
    for j in range(len(Arr2)):
        if (i == j) or (i + j == 4):
            sumArr[i, j] = sumArr[i, j] * sumArr[i, j]
print(sumArr)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]
